name: Web
permissions:
  contents: write
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    name: Build and deploy to gh-pages
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0c366fd6a839edf440554fa01a7085ccba70ac98
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: voidzero-dev/setup-vp@4a524139920f87f9f7080d3b8545acac019e1852
        with:
          node-version: "22"
          cache: true
      - run: vp install
      - run: vp build
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@e247546e78fc69b7e0871042c086f93119e7274b
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
