name: Web
permissions:
  contents: write
on:
  pull_request:
  push:
    branches:
      - main
      - master
      - develop
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
jobs:
  deploy:
    name: Build and deploy to gh-pages
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          ref: ${{ github.event.workflow_run.head_sha }}
      - uses: voidzero-dev/setup-vp@4f5aa3e38c781f1b01e78fb9255527cee8a6efa6 # v1.8.0
        with:
          node-version: "22"
          cache: true
      - run: vp install
      - run: vp build
      - name: Deploy to gh-pages
        uses: JamesIves/github-pages-deploy-action@d92aa235d04922e8f08b40ce78cc5442fcfbfa2f # v4.8.0
        if: ${{ github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master' }}
        with:
          branch: gh-pages
          folder: build
          token: ${{ secrets.GITHUB_TOKEN }}
          single-commit: true
